### ISSUE TITLE
Game not working properly?

### ISSUE THREAD

**Issue by tamilpp25** [Balaji-3009/GuessTheWord#1]
Please fix I love this game

![image](https://github.com/Balaji-3009/GuessTheWord/assets/27989102/69d84845-86ad-47d3-aae3-ee612b61dfea)

**Comment by Balaji-3009** [comment]
fixed in [a396fd9](https://github.com/Balaji-3009/GuessTheWord/commit/a396fd9ca878595c2791c97c9af0cdc0c6dfa887)
